apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding-api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "25%"
      maxSurge: "50%"
  replicas: 3
  selector:
    matchLabels:
      app: onboarding-api
  template:
    metadata:
      labels:
        app: onboarding-api
    spec:
      containers:
        - name: onboarding-api
          image: onboarding-api
          # set to Never so minikube fetches the local build rather than a remote image
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8001
          envFrom:
            - secretRef:
                name: onboarding-secrets
            - configMapRef:
                name: onboarding-config
