apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onboarding-cache
  template:
    metadata:
      labels:
        app: onboarding-cache
    spec:
      containers:
        - name: onboarding-cache
          image: "redis:6.2-alpine"
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
