version: "3"
services:
  db:
    image: postgres:12.2-alpine
    env_file: .env
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_DB
    ports:
      - "$DATABASE_PORT:$DATABASE_PORT"
    volumes:
      - db-data-volume:/var/lib/postgresql/data
      - ./migrations/:/docker-entrypoint-initdb.d/

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        cmd: api
    entrypoint: ["./api"]
    env_file: .env
    depends_on:
      - db
      - redis

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        cmd: consumer
    entrypoint: ["./consumer"]
    env_file: .env
    depends_on:
      - db

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        cmd: gateway
    entrypoint: ["./gateway"]
    env_file: .env
    depends_on:
      - api
    ports:
      - 8000:8000

volumes:
  db-data-volume:
