apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding-database
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: onboarding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onboarding-database
  template:
    metadata:
      labels:
        app: onboarding-database
    spec:
      containers:
        - name: onboarding-database
          image: postgres:14-alpine
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: onboarding-secrets
